### ISSUE TITLE
训练资源和时间没那么充裕，可以提供下跑完的模型结果吗

### ISSUE THREAD

**Issue by jiangliqin** [thu-coai/CDial-GPT#69]
我的邮箱 1063112646@qq.com，可以麻烦提供一份吗，感谢？

**Comment by lemon234071** [comment]
模型不是已经放出来了吗？

**Comment by stdhi** [comment]
Step 3: 生成文本

# YOUR_MODEL_PATH: 你要使用的模型的路径，每次微调后的模型目录保存在./runs/中
python infer.py --model_checkpoint YOUR_MODEL_PATH --datapath data/STC_test.json --out_path STC_result.txt  # 在测试数据上生成回复
python interact.py --model_checkpoint YOUR_MODEL_PATH  # 在命令行中与模型进行交互

**Comment by Jyukai02** [comment]
请问在命令行进行交互的过程中报以下错误是什么问题：
Traceback (most recent call last):
  File "infer.py", line 171, in <module>
    main()
  File "infer.py", line 162, in main
    out_ids = sample_sequence(history, tokenizer, model, args)
  File "infer.py", line 93, in sample_sequence
    logits = logits[0, -1, :] / args.temperature

TypeError: string indices must be integers

**Comment by terminator123** [comment]
> 

output = model(input_ids, token_type_ids=token_type_ids)
logits = output.logits


改成这个可以跑通，但是我的预测结果全是乱码的，不知道为啥
