### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by cuiding** [thu-coai/CDial-GPT#94]
在加载预训练模型时出现这个错误，请问这个错误是怎么回事？

**Comment by silverriver** [comment]
请您提供一下详情：
1. transformer库的版本
2. 加载的哪个模型
3. 出错的指令

**Comment by PlaBerlin** [comment]
transformers  2.1.1

执行步骤：
1. pip install -r requirements.txt
2. git clone https://github.com/thu-coai/CDial-GPT.git
3.cd CDial-GPT
4. git clone https://huggingface.co/thu-coai/CDial-GPT_LCCC-large
5. python train.py --pretrained --model_checkpoint ./CDial-GPT_LCCC-large --data_path data/data_toy.json --scheduler linear

报错内容：
INFO:transformers.modeling_utils:loading weights file ./CDial-GPT_LCCC-large/pytorch_model.bin
Traceback (most recent call last):
  File "train.py", line 238, in <module>
    train()
  File "train.py", line 104, in train
    model = model_class.from_pretrained(args.model_checkpoint)
  File "/home/zkti/anaconda3/envs/gpt/lib/python3.7/site-packages/transformers/modeling_utils.py", line 345, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location='cpu')
  File "/home/zkti/anaconda3/envs/gpt/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/zkti/anaconda3/envs/gpt/lib/python3.7/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by AlexKai1** [comment]
同上

**Comment by AlexKai1** [comment]
“_pickle.UnpicklingError: invalid load key, 'v'.” 
这个报错是因为预训练模型没有下载完整，建议参考下面这位老师的解决方案。
https://github.com/thu-coai/CDial-GPT/issues/74#issuecomment-912299243

ps，
git下载大文件需要安装git lfs插件，参考以下文档进行安装
https://www.jianshu.com/p/493b81544f80
